import type { InferGetStaticPropsType, NextPage } from 'next';
import Head from 'next/head';
import { AllCheesesQuery } from '../gql/graphql';
import hygraphClient, { gql } from '../lib/hygraphClient';

const Home: NextPage<InferGetStaticPropsType<typeof getStaticProps>> = (props) => {
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="container mx-auto flex min-h-screen flex-col items-center justify-center p-4"></main>
    </>
  );
};

const allCheesesQueryDocument = gql`
  query AllCheeses {
    cheeses {
      id
      name
    }
  }
`;

export const getStaticProps = async () => {
  const res = await hygraphClient.request<AllCheesesQuery>(allCheesesQueryDocument);
  return {
    props: res
  };
};

export default Home;
